// backend/controllers/admin/categoryController.js
const sequelize = require("../../config/sequelize"); // Sequelize instance
const initModels = require("../../models/init-models"); // generated by sequelize-auto
const models = initModels(sequelize);

const { Category, Food } = models;

// =========================
// 📌 LẤY DANH SÁCH CATEGORY
// =========================
exports.getAllCategories = async (req, res) => {
  try {
    const categories = await Category.findAll({
      order: [["CategoryId", "DESC"]],
    });
    res.json({ success: true, data: categories });
  } catch (err) {
    console.error("❌ Lỗi lấy categories:", err);
    res.status(500).json({ success: false, message: "Lỗi server" });
  }
};

// =============================
// 📌 LẤY 1 CATEGORY THEO ID
// =============================
exports.getCategoryById = async (req, res) => {
  try {
    const id = req.params.id;
    const category = await Category.findByPk(id);
    if (!category) {
      return res
        .status(404)
        .json({ success: false, message: "Không tìm thấy danh mục" });
    }
    res.json({ success: true, data: category });
  } catch (err) {
    console.error("❌ Lỗi lấy category theo ID:", err);
    res.status(500).json({ success: false, message: "Lỗi server" });
  }
};

// =============================
// 📌 THÊM CATEGORY
// =============================
exports.addCategory = async (req, res) => {
  try {
    let { CategoryName } = req.body;
    if (!CategoryName || !String(CategoryName).trim()) {
      return res
        .status(400)
        .json({ success: false, message: "Thiếu tên danh mục" });
    }
    CategoryName = String(CategoryName).trim();

    // Kiểm tra trùng
    const exists = await Category.findOne({ where: { CategoryName } });
    if (exists) {
      return res.status(400).json({
        success: false,
        message: "Tên danh mục này đã tồn tại.",
      });
    }

    const newCategory = await Category.create({ CategoryName });
    res.status(201).json({
      success: true,
      message: "Thêm danh mục thành công!",
      data: newCategory,
    });
  } catch (err) {
    if (
      err.name === "SequelizeValidationError" ||
      err.name === "SequelizeUniqueConstraintError"
    ) {
      return res
        .status(400)
        .json({ success: false, message: err.errors[0].message });
    }
    console.error("❌ Lỗi thêm category:", err);
    res.status(500).json({ success: false, message: "Lỗi server" });
  }
};

// =============================
// 📌 SỬA CATEGORY
// =============================
exports.editCategory = async (req, res) => {
  try {
    const id = req.params.id;
    const category = await Category.findByPk(id);
    if (!category) {
      return res
        .status(404)
        .json({ success: false, message: "Không tìm thấy danh mục" });
    }

    let { CategoryName } = req.body;
    if (!CategoryName || !String(CategoryName).trim()) {
      return res
        .status(400)
        .json({ success: false, message: "Thiếu tên danh mục" });
    }
    CategoryName = String(CategoryName).trim();

    // Kiểm tra trùng (trừ chính nó)
    const exists = await Category.findOne({
      where: { CategoryName },
    });
    if (exists && exists.CategoryId !== category.CategoryId) {
      return res.status(400).json({
        success: false,
        message: "Tên danh mục này đã tồn tại.",
      });
    }

    category.CategoryName = CategoryName;
    await category.save();

    res.json({ success: true, message: "Cập nhật danh mục thành công!" });
  } catch (err) {
    if (
      err.name === "SequelizeValidationError" ||
      err.name === "SequelizeUniqueConstraintError"
    ) {
      return res
        .status(400)
        .json({ success: false, message: err.errors[0].message });
    }
    console.error("❌ Lỗi sửa category:", err);
    res.status(500).json({ success: false, message: "Lỗi server" });
  }
};

// =============================
// 📌 XÓA CATEGORY
// =============================
exports.deleteCategory = async (req, res) => {
  try {
    const { id } = req.body;
    if (!id) {
      return res
        .status(400)
        .json({ success: false, message: "Thiếu ID danh mục" });
    }

    const category = await Category.findByPk(id);
    if (!category) {
      return res
        .status(404)
        .json({ success: false, message: "Danh mục không tồn tại" });
    }

    // Kiểm tra xem còn món ăn nào thuộc danh mục này không
    const foodCount = await Food.count({ where: { CategoryId: id } });
    if (foodCount > 0) {
      return res.status(409).json({
        success: false,
        message: `Không thể xóa vì có ${foodCount} món ăn đang thuộc danh mục này.`,
      });
    }

    await category.destroy();
    res.json({ success: true, message: "Xóa danh mục thành công!" });
  } catch (err) {
    console.error("❌ Lỗi xóa category:", err);
    res.status(500).json({ success: false, message: "Lỗi server" });
  }
};

// =============================
// 📌 CHECK TÊN TRÙNG (AJAX)
// =============================
exports.checkName = async (req, res) => {
  try {
    const { categoryName } = req.query;
    if (!categoryName)
      return res
        .status(400)
        .json({ success: false, message: "Thiếu tên danh mục" });

    const count = await Category.count({
      where: { CategoryName: categoryName },
    });
    res.json({ success: true, available: count === 0 });
  } catch (err) {
    console.error("❌ Lỗi checkName:", err);
    res.status(500).json({ success: false, message: "Lỗi server" });
  }
};
